package com.example.irregularverbs;

public class SentenceDataBase {
    private final Sentence[] sentences;
    public SentenceDataBase(){
         sentences = new Sentence[]{
                 new Sentence("He has", "bought", "a new car.", "buy"),
                 new Sentence("They have", "completed", "their homework.", "complete"),
                 new Sentence("She has", "read", "the book.", "read"),
                 new Sentence("We have", "finalized", "our vacation plans.", "finalize"),
                 new Sentence("The team has", "won", "the championship.", "win"),
                 new Sentence("I have", "lost", "my keys.", "lose"),
                 new Sentence("The students have", "passed", "the exam.", "pass"),
                 new Sentence("He has", "eaten", "his lunch.", "eat"),
                 new Sentence("She has", "cleaned", "her room.", "clean"),
                 new Sentence("They have", "made", "a decision.", "make"),
                 new Sentence("The company has", "launched", "a new product.", "launch"),
                 new Sentence("We have", "reached", "our destination.", "reach"),
                 new Sentence("He has", "solved", "the puzzle.", "solve"),
                 new Sentence("They have", "built", "a new house.", "build"),
                 new Sentence("She has", "written", "a novel.", "write"),
                 new Sentence("The team has", "scored", "a goal.", "score"),
                 new Sentence("I have", "forgotten", "my password.", "forget"),
                 new Sentence("He has", "finished", "his work.", "finish"),
                 new Sentence("She has", "won", "the competition.", "win"),
                 new Sentence("We have", "arrived", "at the airport.", "arrive"),
                 new Sentence("They have", "created", "a masterpiece.", "create"),
                 new Sentence("The students have", "studied", "for the exam.", "study"),
                 new Sentence("He has", "driven", "the car.", "drive"),
                 new Sentence("She has", "baked", "a cake.", "bake"),
                 new Sentence("We have", "visited", "the museum.", "visit"),
                 new Sentence("They have", "fixed", "the problem.", "fix"),
                 new Sentence("The team has", "practiced", "for the match.", "practice"),
                 new Sentence("I have", "taken", "the train.", "take"),
                 new Sentence("He has", "taught", "the class.", "teach"),
                 new Sentence("She has", "painted", "the wall.", "paint"),
                 new Sentence("We have", "planned", "the trip.", "plan"),
                 new Sentence("They have", "cleaned", "the house.", "clean"),
                 new Sentence("The students have", "learned", "the lesson.", "learn"),
                 new Sentence("He has", "prepared", "the meal.", "prepare"),
                 new Sentence("She has", "played", "the piano.", "play"),
                 new Sentence("We have", "watched", "the movie.", "watch"),
                 new Sentence("They have", "danced", "at the party.", "dance"),
                 new Sentence("The team has", "competed", "in the tournament.", "compete"),
                 new Sentence("I have", "answered", "the question.", "answer"),
                 new Sentence("He has", "attended", "the meeting.", "attend"),
                 new Sentence("She has", "helped", "her friend.", "help"),
                 new Sentence("We have", "discussed", "the issue.", "discuss"),
                 new Sentence("They have", "invited", "their guests.", "invite"),
                 new Sentence("The students have", "performed", "in the play.", "perform"),
                 new Sentence("He has", "fixed", "the leak.", "fix"),
                 new Sentence("She has", "packed", "her bags.", "pack"),
                 new Sentence("We have", "celebrated", "the occasion.", "celebrate"),
                 new Sentence("They have", "achieved", "their goals.", "achieve"),
                 new Sentence("The team has", "praised", "the effort.", "praise"),
                 new Sentence("I have", "finished", "the book.", "finish"),
                 new Sentence("He has", "sent", "the email.", "send"),
                 new Sentence("She has", "studied", "for the test.", "study"),
                 new Sentence("We have", "bought", "the tickets.", "buy"),
                 new Sentence("They have", "completed", "the project.", "complete"),
                 new Sentence("The students have", "passed", "the course.", "pass"),
                 new Sentence("He has", "earned", "the award.", "earn"),
                 new Sentence("She has", "delivered", "the package.", "deliver"),
                 new Sentence("We have", "reached", "our destination.", "reach"),
                 new Sentence("They have", "met", "the deadline.", "meet"),
                 new Sentence("The team has", "won", "the game.", "win"),
                 new Sentence("I have", "found", "the solution.", "find"),
                 new Sentence("He has", "made", "a mistake.", "make"),
                 new Sentence("She has", "taken", "the initiative.", "take"),
                 new Sentence("We have", "organized", "the event.", "organize"),
                 new Sentence("They have", "experienced", "the adventure.", "experience"),
                 new Sentence("The students have", "attended", "the lecture.", "attend"),
                 new Sentence("He has", "helped", "the needy.", "help"),
                 new Sentence("She has", "participated", "in the competition.", "participate"),
                 new Sentence("We have", "decorated", "the house.", "decorate"),
                 new Sentence("They have", "practiced", "the skill.", "practice"),
                 new Sentence("The team has", "improved", "the performance.", "improve"),
                 new Sentence("I have", "followed", "the instructions.", "follow"),
                 new Sentence("He has", "selected", "the option.", "select"),
                 new Sentence("She has", "investigated", "the matter.", "investigate"),
                 new Sentence("We have", "explored", "the area.", "explore"),
                 new Sentence("They have", "discussed", "the plan.", "discuss"),
                 new Sentence("The students have", "achieved", "the goal.", "achieve"),
                 new Sentence("He has", "finished", "the task.", "finish"),
                 new Sentence("She has", "solved", "the problem.", "solve"),
                 new Sentence("We have", "completed", "the assignment.", "complete"),
                 new Sentence("They have", "attended", "the seminar.", "attend"),
                 new Sentence("The team has", "won", "the tournament.", "win"),
                 new Sentence("I have", "reached", "the destination.", "reach"),
                 new Sentence("He has", "received", "the message.", "receive"),
                 new Sentence("She has", "studied", "the lesson.", "study"),
                 new Sentence("We have", "prepared", "the report.", "prepare"),
                 new Sentence("They have", "taken", "the initiative.", "take"),
                 new Sentence("The students have", "learned", "the concept.", "learn"),
                 new Sentence("He has", "performed", "the task.", "perform"),
                 new Sentence("She has", "taken", "the decision.", "take"),
                 new Sentence("We have", "completed", "the project.", "complete"),
                 new Sentence("They have", "attended", "the meeting.", "attend"),
                 new Sentence("The team has", "played", "the match.", "play"),
                 new Sentence("I have", "watched", "the movie.", "watch"),
                 new Sentence("He has", "visited", "the museum.", "visit"),
                 new Sentence("She has", "cleaned", "the house.", "clean"),
                 new Sentence("We have", "celebrated", "the occasion.", "celebrate"),
                 new Sentence("They have", "organized", "the event.", "organize"),
                 new Sentence("The students have", "participated", "in the activity.", "participate"),
                 new Sentence("He has", "helped", "his friend.", "help"),
                 new Sentence("She has", "performed", "the song.", "perform"),
                 new Sentence("We have", "finished", "the meal.", "finish"),
                 new Sentence("They have", "arrived", "at the destination.", "arrive"),
                 new Sentence("The team has", "won", "the championship.", "win"),
                 new Sentence("I have", "started", "the project.", "start"),
                 new Sentence("He has", "completed", "the task.", "complete"),
                 new Sentence("She has", "attended", "the class.", "attend"),
                 new Sentence("We have", "finished", "the race.", "finish"),
                 new Sentence("They have", "submitted", "the assignment.", "submit"),
                 new Sentence("The students have", "studied", "the lesson.", "study"),
                 new Sentence("He has", "practiced", "the skill.", "practice"),
                 new Sentence("She has", "prepared", "the meal.", "prepare"),
                 new Sentence("We have", "planned", "the trip.", "plan"),
                 new Sentence("They have", "received", "the award.", "receive"),
                 new Sentence("The team has", "won", "the match.", "win"),
                 new Sentence("I have", "written", "the report.", "write"),
                 new Sentence("He has", "solved", "the problem.", "solve"),
                 new Sentence("She has", "created", "the artwork.", "create"),
                 new Sentence("We have", "discussed", "the issue.", "discuss"),
                 new Sentence("They have", "completed", "the project.", "complete"),
                 new Sentence("The students have", "attended", "the lecture.", "attend"),
                 new Sentence("He has", "passed", "the exam.", "pass"),
                 new Sentence("She has", "excelled", "in her studies.", "excel"),
                 new Sentence("We have", "achieved", "our goal.", "achieve"),
                 new Sentence("They have", "overcome", "the obstacles.", "overcome"),
                 new Sentence("The team has", "conquered", "the competition.", "conquer"),
                 new Sentence("I have", "purchased", "the item.", "purchase"),
                 new Sentence("He has", "completed", "the course.", "complete"),
                 new Sentence("She has", "attended", "the meeting.", "attend"),
                 new Sentence("We have", "won", "the lottery.", "win"),
                 new Sentence("They have", "completed", "the project.", "complete"),
                 new Sentence("The students have", "submitted", "their assignments.", "submit"),
                 new Sentence("He has", "achieved", "his dream.", "achieve"),
                 new Sentence("She has", "prepared", "the presentation.", "prepare"),
                 new Sentence("We have", "solved", "the problem.", "solve"),
                 new Sentence("They have", "mastered", "the skill.", "master"),
                 new Sentence("The team has", "dominated", "the league.", "dominate")
         };
    }
    public Sentence getExample(int i ){
        return sentences[i];
    }
    public int getSize(){
        return sentences.length;
    }
}
